# Generated by Django 5.2.8 on 2025-11-30 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('medidas', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='loja.produto')),
            ],
        ),
    ]
