# Generated by Django 5.2.8 on 2025-11-30 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de Crédito')], max_length=20)),
                ('status', models.CharField(choices=[('PROCESSAMENTO', 'Em Processamento'), ('APROVADO', 'Pagamento Aprovado'), ('NOTA_EMITIDA', 'Nota Fiscal Emitida'), ('PREPARACAO', 'Em Preparação'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Recebido/Entregue'), ('REPROVADO', 'Pagamento Reprovado'), ('CANCELADO', 'Cancelado'), ('SOLICITACAO_DEVOLUCAO', 'Solicitação de Devolução'), ('EM_DEVOLUCAO', 'Em Devolução'), ('DEVOLVIDO', 'Devolvido'), ('DEVOLUCAO_CANCELADA', 'Devolução Cancelada')], default='PROCESSAMENTO', max_length=30)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cartao_numero', models.CharField(blank=True, max_length=16, null=True)),
                ('cartao_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cartao_validade', models.CharField(blank=True, max_length=5, null=True)),
                ('cartao_codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_na_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedido')),
            ],
        ),
    ]
